name = "coding-club-worker"
main = "src/index.ts"
compatibility_date = "2026-04-05"

# Set this with: wrangler secret put CLERK_SECRET_KEY
# (do not store real secret in this file)

[vars]
# Comma-separated admin emails (lowercase recommended)
ADMIN_EMAILS = "admin1@psbbschools.edu.in,admin2@psbbschools.edu.in"

[[d1_databases]]
binding = "DB"
database_name = "coding-club-db"
database_id = "be6fea66-8269-467e-a1c4-c95925546c90"
migrations_dir = "../database/migrations"

[[kv_namespaces]]
binding = "APP_STATE"
id = "964f0061958e4d3f8ba3851f9ba8e727"
preview_id = "5734318764204f1981c707369eee141a"
